language: python
sudo: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip


env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - TESTDATA_DIR=$HOME/testdata
  matrix:
   # - GDALVERSION="2.1.3"
   # - GDALVERSION="2.2.1"
   # - GDALVERSION="2.2.0"
   # - GDALVERSION="trunk"
matrix:
  allow_failures:
    - env: GDALVERSION="trunk"

addons:
  apt:
    packages:
    #- gdal-bin
    #- libproj-dev
    #- libgdal-dev
    - libspatialite-dev
    - swig2.0
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin python-gdal libproj-dev libgdal-dev -y
  - pip install -U pip
  #- . ./pyroSAR/install/travis_gdal_install.sh
  #- export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  #- export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  #- export PYTHONPATH=$GDALINST/gdal-$GDALVERSION/lib/python2.7/site-packages
install:
  #- "if [ \"$GDALVERSION\" == \"trunk\" -o $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - pwd
  - travis-wait 40 . ./pyroSAR/install/download_testdata.sh
script:
  - pwd
  - pytest


